
--Linea para desbloquear la consola:
SET SERVEROUTPUT ON;

--Insertar una pantalla:
CREATE OR REPLACE PROCEDURE P_INSERTAR_PANTALLA(
    P_COD_USU TBL_PANTALLAS.CODIGO_USUARIO%TYPE,
    P_COD_MAD TBL_PANTALLAS.CODIGO_MADUREZ%TYPE,
    P_COD_IDI_LEN TBL_PANTALLAS.CODIGO_IDIOMA_LENGUAJE%TYPE,
    P_COD_EST_SUB TBL_PANTALLAS.CODIGO_ESTILO_SUB%TYPE,
    P_COD_CONF_REP TBL_PANTALLAS.CODIGO_CONFIG_REPRODUCCION%TYPE,
    P_NOM_PAN TBL_PANTALLAS.NOMBRE_PANTALLA%TYPE
) AS

BEGIN
    INSERT INTO TBL_PANTALLAS (CODIGO_PANTALLA, CODIGO_USUARIO, CODIGO_MADUREZ, CODIGO_IDIOMA_LENGUAJE, CODIGO_ESTILO_SUB, CODIGO_CONFIG_REPRODUCCION, NOMBRE_PANTALLA, CORREO_PANTALLA, URL_IMG_PANTALLA) VALUES (SEQ_COD_PANTALLA.NEXTVAL, P_COD_USU, P_COD_MAD, P_COD_IDI_LEN, P_COD_EST_SUB, P_COD_CONF_REP, P_NOM_PAN, NULL, NULL);
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLCODE || '-'||SQLERRM);
    ROLLBACK;

END;

--Ejecucion:
CALL P_INSERTAR_PANTALLA(2, 3, 1, 0, 0, 'Nombre 1');

--Actualizar info pantalla
CREATE OR REPLACE PROCEDURE P_ACTUALIZAR_PANTALLA(
    P_CODIGO_USUARIO TBL_PANTALLAS.CODIGO_USUARIO%TYPE,
    P_CODIGO_MADUREZ TBL_PANTALLAS.CODIGO_MADUREZ%TYPE,
    P_CODIGO_IDIOMA_LENGUAJE TBL_PANTALLAS.CODIGO_IDIOMA_LENGUAJE%TYPE,
    P_CODIGO_ESTILO_SUB TBL_PANTALLAS.CODIGO_ESTILO_SUB%TYPE,
    P_CODIGO_CONFIG_REPRO TBL_PANTALLAS.CODIGO_CONFIG_REPRODUCCION%TYPE,
    P_NOMBRE_PANTALLA TBL_PANTALLAS.NOMBRE_PANTALLA%TYPE,
    P_CORREO_PANTALLA TBL_PANTALLAS.CORREO_PANTALLA%TYPE,
    P_URL_IMG_PANTALLA TBL_PANTALLAS.URL_IMG_PANTALLA%TYPE
) AS

BEGIN
    UPDATE TBL_PANTALLAS 
    SET  TBL_PANTALLAS.CODIGO_USUARIO%TYPE = P_CODIGO_MADUREZ,
         TBL_PANTALLAS.CODIGO_IDIOMA_LENGUAJE%TYPE = P_CODIGO_IDIOMA_LENGUAJE,
         TBL_PANTALLAS.CODIGO_ESTILO_SUB%TYPE = P_CODIGO_ESTILO_SUB,
         TBL_PANTALLAS.CODIGO_CONFIG_REPRODUCCION%TYPE = P_CODIGO_CONFIG_REPRO,
         TBL_PANTALLAS.NOMBRE_PANTALLA%TYPE = P_NOMBRE_PANTALLA,
         TBL_PANTALLAS.CORREO_PANTALLA%TYPE = P_CORREO_PANTALLA,
         TBL_PANTALLAS.URL_IMG_PANTALLA%TYPE = P_URL_IMG_PANTALLA
    WHERE 
    COMMIT;

EXCEPTION
    WHEN OTHER THEN
    DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLCODE || '-'||SQLERRM);
    ROLLBACK;

END;



----Actualiza la configuracion de reproduccion 
create or replace PROCEDURE P_ACTUALIZAR_CONFIG_REP(   
    P_CODIGO_PANTALLA IN  TBL_PANTALLAS.CODIGO_PANTALLA%TYPE,
    P_CODIGO_T_USO_DATO  IN TBL_TIPO_USO_DATOS.CODIGO_TIPO_USO_DATOS%TYPE, 
    P_CODIGO_T_REPROD IN  TBL_TIPO_REPRODUCCION.CODIGO_TIPO_REPRODUCCION%TYPE,
    p_mensaje OUT VARCHAR2,
    p_codigo_resultado OUT NUMBER
) AS
    V_CODIGO_CONFIG_REP NUMBER;
BEGIN  

    SELECT CODIGO_CONFIG_REPRODUCCION INTO V_CODIGO_CONFIG_REP
    FROM TBL_PANTALLAS
    WHERE CODIGO_PANTALLA = P_CODIGO_PANTALLA;

    UPDATE TBL_REPRODUCCION
    SET  TBL_REPRODUCCION.CODIGO_TIPO_USO_DATOS = P_CODIGO_T_USO_DATO,
         TBL_REPRODUCCION.CODIGO_TIPO_REPRODUCCION= P_CODIGO_T_REPROD 
    WHERE  TBL_REPRODUCCION.CODIGO_CONFIG_REPRODUCCION = V_CODIGO_CONFIG_REP;
    COMMIT;
    p_mensaje := 'Actualizado'; 
    p_codigo_resultado:=1; 

EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        p_mensaje:= 'Error: ' || SQLCODE || '-'||SQLERRM;
        p_codigo_resultado:=0;
END;



----Actualiza la info de configuracion de subtitulos 
create or replace PROCEDURE P_ACTUALIZAR_CONFIG_SUB(   
    P_CODIGO_PANTALLA IN  TBL_PANTALLAS.CODIGO_PANTALLA%TYPE,
    P_NOMBRE_FUENTE  IN  TBL_TIPOS_FUENTES.NOMBRE_TIPO_FUENTE%TYPE, 
    P_COD_RGB_COLOR_FUENTE IN  TBL_COLORES.CODIGO_RGB%TYPE,
    P_TAMANIO_FUENTE  IN  TBL_ESTILOS_SUBTITULOS.TAMANIO_FUENTE%TYPE,
    P_NOMBRE_SOMBRA IN   TBL_SOMBRAS_FUENTES.NOMBRE_SOMBRA%TYPE,
    P_COD_RGB_COLOR_SOMBRA IN TBL_COLORES.CODIGO_RGB%TYPE,                    
    P_COD_RGB_COLOR_FONDO  IN  TBL_COLORES.CODIGO_RGB%TYPE,
    P_COD_RGB_COLOR_VENTANA IN TBL_COLORES.CODIGO_RGB%TYPE,
    p_mensaje OUT VARCHAR2,
    p_codigo_resultado OUT NUMBER
) AS
    V_CODIGO_ESTILO NUMBER;
    V_CODIGO_TIPO_FUENTE NUMBER;
    V_CODIGO_COLOR_FUENTE NUMBER;
    V_CODIGO_SOMBRA_FUENTE NUMBER;
    V_CODIGO_COLOR_SOMBRA  NUMBER;
    V_CODIGO_COLOR_FONDO NUMBER;
    V_CODIGO_COLOR_VENTANA NUMBER;
BEGIN  

    SELECT CODIGO_ESTILO_SUB INTO V_CODIGO_ESTILO
    FROM TBL_PANTALLAS
    WHERE CODIGO_PANTALLA = P_CODIGO_PANTALLA;

    SELECT  CODIGO_TIPO_FUENTE INTO V_CODIGO_TIPO_FUENTE
    FROM TBL_TIPOS_FUENTES
    WHERE UPPER(NOMBRE_TIPO_FUENTE) = UPPER(P_NOMBRE_FUENTE);

    SELECT  CODIGO_COLOR INTO V_CODIGO_COLOR_FUENTE
    FROM  TBL_COLORES
    WHERE CODIGO_RGB = P_COD_RGB_COLOR_FUENTE;

    SELECT  CODIGO_SOMBRA INTO V_CODIGO_SOMBRA_FUENTE
    FROM  TBL_SOMBRAS_FUENTES
    WHERE UPPER(NOMBRE_SOMBRA) = UPPER(P_NOMBRE_SOMBRA);     

    SELECT  CODIGO_COLOR INTO V_CODIGO_COLOR_SOMBRA
    FROM  TBL_COLORES
    WHERE CODIGO_RGB = P_COD_RGB_COLOR_SOMBRA;

    SELECT  CODIGO_COLOR INTO V_CODIGO_COLOR_FONDO
    FROM  TBL_COLORES
    WHERE CODIGO_RGB = P_COD_RGB_COLOR_FONDO;

    SELECT  CODIGO_COLOR INTO V_CODIGO_COLOR_VENTANA
    FROM  TBL_COLORES
    WHERE CODIGO_RGB = P_COD_RGB_COLOR_VENTANA;

    UPDATE TBL_ESTILOS_SUBTITULOS
    SET  TBL_ESTILOS_SUBTITULOS.CODIGO_TIPO_FUENTE = V_CODIGO_TIPO_FUENTE,
         TBL_ESTILOS_SUBTITULOS.CODIGO_SOMBRA=V_CODIGO_SOMBRA_FUENTE,
         TBL_ESTILOS_SUBTITULOS.CODIGO_COLOR_FUENTE= V_CODIGO_COLOR_FUENTE,
         TBL_ESTILOS_SUBTITULOS.CODIGO_COLOR_SOMBRA= V_CODIGO_COLOR_SOMBRA,
         TBL_ESTILOS_SUBTITULOS.CODIGO_COLOR_FONDO= V_CODIGO_COLOR_FONDO,
         TBL_ESTILOS_SUBTITULOS.CODIGO_COLOR_VENTANA= V_CODIGO_COLOR_VENTANA,
         TBL_ESTILOS_SUBTITULOS.TAMANIO_FUENTE = P_TAMANIO_FUENTE
    WHERE  TBL_ESTILOS_SUBTITULOS.CODIGO_ESTILO_SUB = V_CODIGO_ESTILO;
    COMMIT;


    p_mensaje := 'Registro creado'; 
    p_codigo_resultado:=1; 

EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLCODE || '-'||SQLERRM);
        ROLLBACK;
        p_mensaje:= 'Error al actualizar registro: ' || SQLCODE || '-'||SQLERRM;
        p_codigo_resultado:=0;
END;



-----Crea un nuevo registro de configuracion de reproduccion y este sustituye al predefinido, la primera vez que se utiliza.

create or replace PROCEDURE P_CREAR_CONFIG_REP(   
    P_CODIGO_PANTALLA IN  TBL_PANTALLAS.CODIGO_PANTALLA%TYPE,
    P_MENSAJE OUT VARCHAR2,
    P_CODIGO_RESULTADO OUT NUMBER
) AS
    V_CODIGO_CONFIG_REP NUMBER;
    V_COD_SEQ_CONFIG_REP NUMBER;
BEGIN 
    SELECT CODIGO_CONFIG_REPRODUCCION INTO V_CODIGO_CONFIG_REP
    FROM TBL_PANTALLAS
    WHERE CODIGO_PANTALLA = P_CODIGO_PANTALLA;

    IF (V_CODIGO_CONFIG_REP=0) THEN
        V_COD_SEQ_CONFIG_REP:= SEQ_COD_CONFIG_REP.nextval;
        INSERT INTO TBL_REPRODUCCION(
            CODIGO_CONFIG_REPRODUCCION,
            CODIGO_TIPO_USO_DATOS,
            CODIGO_TIPO_REPRODUCCION 
        ) VALUES (
            V_COD_SEQ_CONFIG_REP,
            3,
            2
        );
      UPDATE TBL_PANTALLAS
      SET    TBL_PANTALLAS.CODIGO_CONFIG_REPRODUCCION = V_COD_SEQ_CONFIG_REP
      WHERE  TBL_PANTALLAS.CODIGO_PANTALLA = P_CODIGO_PANTALLA;
      COMMIT;
      P_MENSAJE := 'Registro creado';
      P_CODIGO_RESULTADO:=1;
    ELSE
        P_MENSAJE := 'Ya existe registro';
        P_CODIGO_RESULTADO:=0;
    END IF;
EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLCODE || '-'||SQLERRM);
        ROLLBACK;
        P_MENSAJE:= 'Error al verificar: ' || SQLCODE || '-'||SQLERRM;
        P_CODIGO_RESULTADO:=2;
END;


---------------Crea un nuevo registro de estilo subtitulo y este sustituye al predefinido la primera vez que se utiliza.
create or replace PROCEDURE P_CREAR_ESTILO_SUB(   
    P_CODIGO_PANTALLA IN  TBL_PANTALLAS.CODIGO_PANTALLA%TYPE,
    P_MENSAJE OUT VARCHAR2,
    P_CODIGO_RESULTADO OUT NUMBER
) AS
    V_CODIGO_ESTILO NUMBER;
    V_COD_SEQ_ESTILO NUMBER;
BEGIN 
    SELECT CODIGO_ESTILO_SUB INTO V_CODIGO_ESTILO
    FROM TBL_PANTALLAS
    WHERE CODIGO_PANTALLA = P_CODIGO_PANTALLA;

    IF (V_CODIGO_ESTILO = 0) THEN
        V_COD_SEQ_ESTILO := SEQ_COD_ESTILO_SUBTITULO.nextval;
        INSERT INTO TBL_ESTILOS_SUBTITULOS(
            CODIGO_ESTILO_SUB,
            CODIGO_TIPO_FUENTE,
            CODIGO_SOMBRA,
            CODIGO_COLOR_FUENTE,
            CODIGO_COLOR_SOMBRA,
            CODIGO_COLOR_FONDO,
            CODIGO_COLOR_VENTANA,
            TAMANIO_FUENTE
        ) VALUES (
            V_COD_SEQ_ESTILO,
            6,
            2,
            2,
            3,
            1,
            1,
            '20pt'
        );
      UPDATE TBL_PANTALLAS
      SET    TBL_PANTALLAS.CODIGO_ESTILO_SUB = V_COD_SEQ_ESTILO
      WHERE  TBL_PANTALLAS.CODIGO_PANTALLA = P_CODIGO_PANTALLA;
      COMMIT;
      P_MENSAJE := 'Registro creado';
      P_CODIGO_RESULTADO:=1;
    ELSE
        P_MENSAJE := 'Ya existe registro';
        P_CODIGO_RESULTADO:=0;
    END IF;
EXCEPTION
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLCODE || '-'||SQLERRM);
        ROLLBACK;
        P_MENSAJE:= 'Error al verificar: ' || SQLCODE || '-'||SQLERRM;
        P_CODIGO_RESULTADO:=0;
END;


-------Trae la informacion de la configuracion actual de reproduccion de una pantalla.

create or replace PROCEDURE P_INICIALIZAR_CONFIG_REP(  
    P_CODIGO_PANTALLA IN  TBL_PANTALLAS.CODIGO_PANTALLA%TYPE,
    P_CODIGO_T_USO_DATO  OUT TBL_TIPO_USO_DATOS.CODIGO_TIPO_USO_DATOS%TYPE, 
    P_CODIGO_T_REPROD OUT  TBL_TIPO_REPRODUCCION.CODIGO_TIPO_REPRODUCCION%TYPE,
    p_mensaje OUT VARCHAR2,
    p_codigo_resultado OUT NUMBER
) AS
    V_CODIGO_CONFIG_R NUMBER;
BEGIN 
    SELECT CODIGO_CONFIG_REPRODUCCION INTO V_CODIGO_CONFIG_R
    FROM TBL_PANTALLAS
    WHERE CODIGO_PANTALLA =  P_CODIGO_PANTALLA;

    SELECT  CODIGO_TIPO_USO_DATOS, CODIGO_TIPO_REPRODUCCION INTO 
    P_CODIGO_T_USO_DATO,P_CODIGO_T_REPROD
    FROM TBL_REPRODUCCION 
    WHERE CODIGO_CONFIG_REPRODUCCION = V_CODIGO_CONFIG_R; 

    p_mensaje := 'Registro inicializado'; 
    p_codigo_resultado:=1;

EXCEPTION
        WHEN OTHERS THEN
        p_mensaje:= 'Error al inicializar: ' || SQLCODE || '-'||SQLERRM;
        p_codigo_resultado:=0;
END;


------------------Trae la informacion de la configuracion actual del estilo de reproduccion de una pantalla

create or replace PROCEDURE P_INICIALIZAR_CONFIG_SUB(   
    P_CODIGO_PANTALLA IN  TBL_PANTALLAS.CODIGO_PANTALLA%TYPE,
    P_NOMBRE_FUENTE  OUT  TBL_TIPOS_FUENTES.NOMBRE_TIPO_FUENTE%TYPE, 
    P_COD_RGB_COLOR_FUENTE OUT  TBL_COLORES.CODIGO_RGB%TYPE,
    P_TAMANIO_FUENTE  OUT  TBL_ESTILOS_SUBTITULOS.TAMANIO_FUENTE%TYPE,
    P_NOMBRE_SOMBRA OUT   TBL_SOMBRAS_FUENTES.NOMBRE_SOMBRA%TYPE,
    P_COD_RGB_COLOR_SOMBRA OUT TBL_COLORES.CODIGO_RGB%TYPE,                    
    P_COD_RGB_COLOR_FONDO  OUT  TBL_COLORES.CODIGO_RGB%TYPE,
    P_COD_RGB_COLOR_VENTANA OUT TBL_COLORES.CODIGO_RGB%TYPE,
    p_mensaje OUT VARCHAR2,
    p_codigo_resultado OUT NUMBER
) AS
    V_CODIGO_ESTILO NUMBER;
BEGIN 
    SELECT CODIGO_ESTILO_SUB INTO V_CODIGO_ESTILO
    FROM TBL_PANTALLAS
    WHERE CODIGO_PANTALLA =  P_CODIGO_PANTALLA; ---Parametro de codigo_pantalla 

    SELECT B.NOMBRE_TIPO_FUENTE,C.CODIGO_RGB as COD_COLOR_FUENTE, D.CODIGO_RGB as COD_COLOR_SOMBRA,
           E.CODIGO_RGB as COD_COLOR_FONDO,F.CODIGO_RGB as COD_COLOR_VENTANA, A.TAMANIO_FUENTE,
           G.NOMBRE_SOMBRA INTO P_NOMBRE_FUENTE,P_COD_RGB_COLOR_FUENTE,P_COD_RGB_COLOR_SOMBRA,P_COD_RGB_COLOR_FONDO,
           P_COD_RGB_COLOR_VENTANA, P_TAMANIO_FUENTE,P_NOMBRE_SOMBRA
    FROM TBL_ESTILOS_SUBTITULOS A
    LEFT JOIN TBL_TIPOS_FUENTES B
    ON (A.CODIGO_TIPO_FUENTE = B.CODIGO_TIPO_FUENTE)
    LEFT JOIN TBL_COLORES C  --COLOR FUENTE
    ON (A.CODIGO_COLOR_FUENTE = C.CODIGO_COLOR)
    LEFT JOIN TBL_COLORES D  --COLOR SOMBRA
    ON (A.CODIGO_COLOR_SOMBRA = D.CODIGO_COLOR)
    LEFT JOIN TBL_COLORES E  --COLOR FONDO
    ON (A.CODIGO_COLOR_FONDO = E.CODIGO_COLOR)
    LEFT JOIN TBL_COLORES F  --COLOR VENTANA
    ON (A.CODIGO_COLOR_VENTANA= F.CODIGO_COLOR)
    LEFT JOIN TBL_SOMBRAS_FUENTES G  
    ON (A.CODIGO_SOMBRA= G.CODIGO_SOMBRA)
    WHERE A.CODIGO_ESTILO_SUB = V_CODIGO_ESTILO; 

    p_mensaje := 'Registro inicializado'; 
    p_codigo_resultado:=1;

EXCEPTION
        WHEN OTHERS THEN
        p_mensaje:= 'Error al inicializar: ' || SQLCODE || '-'||SQLERRM;
        p_codigo_resultado:=0;
END;