
--Secuencia de Pantallas
CREATE SEQUENCE SEQ_COD_PANTALLA
INCREMENT BY 1
START WITH 1;


CREATE SEQUENCE SEQ_COD_ESTILO_SUBTITULO
INCREMENT BY 1
START WITH 1;


CREATE SEQUENCE SEQ_COD_CONFIG_REP
INCREMENT BY 1
START WITH 1;