
--Secuencia de Pantallas
CREATE SEQUENCE SEQ_COD_PANTALLA
INCREMENT BY 1
START WITH 1;


--***** SIGNE *****
--Secuencia de Contenido
CREATE SEQUENCE SEQ_COD_CONTENIDO
INCREMENT BY 1
START WITH 1;

--Secuencia de Registro de temporada
CREATE SEQUENCE SEQ_COD_REG_TEMPORADA
INCREMENT BY 1
START WITH 1;

--Secuencia de Codigo episodio
CREATE SEQUENCE SEQ_COD_EPISODIO
INCREMENT BY 1
START WITH 1;


--Secuencia Usuario
CREATE SEQUENCE SEQ_COD_USUARIO
INCREMENT BY 1
START WITH 1;

--Secuencia registro tarjeta
CREATE SEQUENCE SEQ_COD_REGIS_TARJ
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE SEQ_COD_ESTILO_SUBTITULO
INCREMENT BY 1
START WITH 1;


CREATE SEQUENCE SEQ_COD_CONFIG_REP
INCREMENT BY 1
START WITH 1;